// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acl.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id)
SELECT $1::uuid, $2::uuid
FROM groups g
WHERE g.id = $1::uuid
  AND g.tenant_id = $3::uuid AND g.org_id = $4::uuid
ON CONFLICT (group_id, user_id) DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID  string `json:"group_id"`
	UserID   string `json:"user_id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember,
		arg.GroupID,
		arg.UserID,
		arg.TenantID,
		arg.OrgID,
	)
	return err
}

const createGrant = `-- name: CreateGrant :one
INSERT INTO acl_grants (tenant_id, org_id, resource_type, resource_id, principal_type, principal_id, permission, granted_by)
VALUES (
  $1::uuid, $2::uuid,
  $3::acl_resource_type, $4::uuid,
  $5::acl_principal_type, $6::uuid,
  $7::acl_permission, $8::uuid)
ON CONFLICT (resource_type, resource_id, principal_type, principal_id, permission) DO NOTHING
RETURNING id
`

type CreateGrantParams struct {
	TenantID      string           `json:"tenant_id"`
	OrgID         string           `json:"org_id"`
	ResourceType  AclResourceType  `json:"resource_type"`
	ResourceID    string           `json:"resource_id"`
	PrincipalType AclPrincipalType `json:"principal_type"`
	PrincipalID   string           `json:"principal_id"`
	Permission    AclPermission    `json:"permission"`
	GrantedBy     *string          `json:"granted_by"`
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (string, error) {
	row := q.db.QueryRow(ctx, createGrant,
		arg.TenantID,
		arg.OrgID,
		arg.ResourceType,
		arg.ResourceID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Permission,
		arg.GrantedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (tenant_id, org_id, name, created_by)
VALUES ($1::uuid, $2::uuid, $3, $4::uuid)
RETURNING id, tenant_id, org_id, name, created_by, created_at
`

type CreateGroupParams struct {
	TenantID  string  `json:"tenant_id"`
	OrgID     string  `json:"org_id"`
	Name      string  `json:"name"`
	CreatedBy *string `json:"created_by"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.TenantID,
		arg.OrgID,
		arg.Name,
		arg.CreatedBy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrgID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGrant = `-- name: DeleteGrant :execrows
DELETE FROM acl_grants
WHERE id = $1::uuid
  AND tenant_id = $2::uuid AND org_id = $3::uuid
`

type DeleteGrantParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrant, arg.ID, arg.TenantID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGrantsForResource = `-- name: DeleteGrantsForResource :execrows
DELETE FROM acl_grants
WHERE tenant_id = $1::uuid AND org_id = $2::uuid
  AND resource_type = $3::acl_resource_type
  AND resource_id = $4::uuid
`

type DeleteGrantsForResourceParams struct {
	TenantID     string          `json:"tenant_id"`
	OrgID        string          `json:"org_id"`
	ResourceType AclResourceType `json:"resource_type"`
	ResourceID   string          `json:"resource_id"`
}

func (q *Queries) DeleteGrantsForResource(ctx context.Context, arg DeleteGrantsForResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrantsForResource,
		arg.TenantID,
		arg.OrgID,
		arg.ResourceType,
		arg.ResourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups
WHERE id = $1::uuid
  AND tenant_id = $2::uuid AND org_id = $3::uuid
`

type DeleteGroupParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, arg.ID, arg.TenantID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const grantTargetExists = `-- name: GrantTargetExists :one
SELECT EXISTS (
  SELECT 1 FROM documents d
  WHERE $1::acl_resource_type = 'document'
    AND d.id = $2::uuid
    AND d.tenant_id = $3::uuid AND d.org_id = $4::uuid
  UNION ALL
  SELECT 1 FROM folders f
  WHERE $1::acl_resource_type = 'folder'
    AND f.id = $2::uuid
    AND f.tenant_id = $3::uuid AND f.org_id = $4::uuid
) AS exists
`

type GrantTargetExistsParams struct {
	ResourceType AclResourceType `json:"resource_type"`
	ResourceID   string          `json:"resource_id"`
	TenantID     string          `json:"tenant_id"`
	OrgID        string          `json:"org_id"`
}

// Returns true when the (resource_type, resource_id) refers to an existing
// document or folder in the caller's tenant/org, used to validate a grant target.
func (q *Queries) GrantTargetExists(ctx context.Context, arg GrantTargetExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, grantTargetExists,
		arg.ResourceType,
		arg.ResourceID,
		arg.TenantID,
		arg.OrgID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isDocumentVisibleToUser = `-- name: IsDocumentVisibleToUser :one
WITH RECURSIVE folder_chain(folder_id, parent_id, is_restricted, path) AS (
  SELECT f.id, f.parent_id, f.is_restricted, ARRAY[f.id]
  FROM folders f JOIN documents d ON d.folder_id = f.id
  WHERE d.id = $5::uuid
    AND d.tenant_id = $6::uuid AND d.org_id = $3::uuid
  UNION ALL
  SELECT pf.id, pf.parent_id, pf.is_restricted, fc.path || pf.id
  FROM folders pf JOIN folder_chain fc ON pf.id = fc.parent_id
  WHERE NOT pf.id = ANY(fc.path) AND array_length(fc.path, 1) < 100
)
SELECT
  $1::boolean
  OR d.owner_id = $2::uuid
  OR (NOT d.is_restricted AND NOT EXISTS (SELECT 1 FROM folder_chain WHERE is_restricted))
  OR EXISTS (SELECT 1 FROM acl_grants g
       WHERE g.resource_type='document' AND g.resource_id=d.id AND g.permission='read'
         AND g.org_id = $3::uuid
         AND ((g.principal_type='user'  AND g.principal_id=$2::uuid)
           OR (g.principal_type='group' AND g.principal_id = ANY($4::uuid[]))))
  OR EXISTS (SELECT 1 FROM acl_grants g
       WHERE g.resource_type='folder' AND g.resource_id IN (SELECT folder_id FROM folder_chain)
         AND g.permission='read'
         AND g.org_id = $3::uuid
         AND ((g.principal_type='user'  AND g.principal_id=$2::uuid)
           OR (g.principal_type='group' AND g.principal_id = ANY($4::uuid[])))) AS visible
FROM documents d
WHERE d.id = $5::uuid
  AND d.tenant_id = $6::uuid AND d.org_id = $3::uuid
`

type IsDocumentVisibleToUserParams struct {
	IsAdmin    bool     `json:"is_admin"`
	UserID     string   `json:"user_id"`
	OrgID      string   `json:"org_id"`
	GroupIds   []string `json:"group_ids"`
	DocumentID string   `json:"document_id"`
	TenantID   string   `json:"tenant_id"`
}

func (q *Queries) IsDocumentVisibleToUser(ctx context.Context, arg IsDocumentVisibleToUserParams) (*bool, error) {
	row := q.db.QueryRow(ctx, isDocumentVisibleToUser,
		arg.IsAdmin,
		arg.UserID,
		arg.OrgID,
		arg.GroupIds,
		arg.DocumentID,
		arg.TenantID,
	)
	var visible *bool
	err := row.Scan(&visible)
	return visible, err
}

const isDocumentWritableToUser = `-- name: IsDocumentWritableToUser :one
WITH RECURSIVE folder_chain(folder_id, parent_id, is_restricted, path) AS (
  SELECT f.id, f.parent_id, f.is_restricted, ARRAY[f.id]
  FROM folders f JOIN documents d ON d.folder_id = f.id
  WHERE d.id = $5::uuid
    AND d.tenant_id = $6::uuid AND d.org_id = $3::uuid
  UNION ALL
  SELECT pf.id, pf.parent_id, pf.is_restricted, fc.path || pf.id
  FROM folders pf JOIN folder_chain fc ON pf.id = fc.parent_id
  WHERE NOT pf.id = ANY(fc.path) AND array_length(fc.path, 1) < 100
)
SELECT
  $1::boolean
  OR d.owner_id = $2::uuid
  OR (NOT d.is_restricted AND NOT EXISTS (SELECT 1 FROM folder_chain WHERE is_restricted))
  OR EXISTS (SELECT 1 FROM acl_grants g
       WHERE g.resource_type='document' AND g.resource_id=d.id AND g.permission IN ('write','delete')
         AND g.org_id = $3::uuid
         AND ((g.principal_type='user'  AND g.principal_id=$2::uuid)
           OR (g.principal_type='group' AND g.principal_id = ANY($4::uuid[]))))
  OR EXISTS (SELECT 1 FROM acl_grants g
       WHERE g.resource_type='folder' AND g.resource_id IN (SELECT folder_id FROM folder_chain)
         AND g.permission IN ('write','delete')
         AND g.org_id = $3::uuid
         AND ((g.principal_type='user'  AND g.principal_id=$2::uuid)
           OR (g.principal_type='group' AND g.principal_id = ANY($4::uuid[])))) AS writable
FROM documents d
WHERE d.id = $5::uuid
  AND d.tenant_id = $6::uuid AND d.org_id = $3::uuid
`

type IsDocumentWritableToUserParams struct {
	IsAdmin    bool     `json:"is_admin"`
	UserID     string   `json:"user_id"`
	OrgID      string   `json:"org_id"`
	GroupIds   []string `json:"group_ids"`
	DocumentID string   `json:"document_id"`
	TenantID   string   `json:"tenant_id"`
}

func (q *Queries) IsDocumentWritableToUser(ctx context.Context, arg IsDocumentWritableToUserParams) (*bool, error) {
	row := q.db.QueryRow(ctx, isDocumentWritableToUser,
		arg.IsAdmin,
		arg.UserID,
		arg.OrgID,
		arg.GroupIds,
		arg.DocumentID,
		arg.TenantID,
	)
	var writable *bool
	err := row.Scan(&writable)
	return writable, err
}

const listGrantsByResource = `-- name: ListGrantsByResource :many
SELECT id, tenant_id, org_id, resource_type, resource_id, principal_type, principal_id, permission, granted_by, created_at
FROM acl_grants
WHERE tenant_id = $1::uuid AND org_id = $2::uuid
  AND resource_type = $3::acl_resource_type
  AND resource_id = $4::uuid
ORDER BY created_at ASC
`

type ListGrantsByResourceParams struct {
	TenantID     string          `json:"tenant_id"`
	OrgID        string          `json:"org_id"`
	ResourceType AclResourceType `json:"resource_type"`
	ResourceID   string          `json:"resource_id"`
}

func (q *Queries) ListGrantsByResource(ctx context.Context, arg ListGrantsByResourceParams) ([]AclGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsByResource,
		arg.TenantID,
		arg.OrgID,
		arg.ResourceType,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AclGrant{}
	for rows.Next() {
		var i AclGrant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.ResourceType,
			&i.ResourceID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Permission,
			&i.GrantedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupIDsForUser = `-- name: ListGroupIDsForUser :many
SELECT gm.group_id FROM group_members gm JOIN groups g ON g.id = gm.group_id
WHERE gm.user_id = $1::uuid AND g.org_id = $2::uuid
`

type ListGroupIDsForUserParams struct {
	UserID string `json:"user_id"`
	OrgID  string `json:"org_id"`
}

func (q *Queries) ListGroupIDsForUser(ctx context.Context, arg ListGroupIDsForUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGroupIDsForUser, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var group_id string
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, tenant_id, org_id, name, created_by, created_at
FROM groups
WHERE tenant_id = $1::uuid AND org_id = $2::uuid
ORDER BY name ASC
`

type ListGroupsParams struct {
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.TenantID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleDocuments = `-- name: ListVisibleDocuments :many
WITH RECURSIVE folder_ancestors AS (
  SELECT f.id AS origin_folder_id, f.id AS ancestor_id, f.parent_id, f.is_restricted, ARRAY[f.id] AS path
  FROM folders f WHERE f.org_id = $2::uuid
  UNION ALL
  SELECT fa.origin_folder_id, pf.id, pf.parent_id, pf.is_restricted, fa.path || pf.id
  FROM folders pf JOIN folder_ancestors fa ON pf.id = fa.parent_id
  WHERE NOT pf.id = ANY(fa.path) AND array_length(fa.path, 1) < 100
)
SELECT d.id, d.tenant_id, d.org_id, d.folder_id, d.owner_id, d.title,
       d.doc_type, d.status, d.language, d.created_at
FROM documents d
WHERE d.tenant_id = $1::uuid AND d.org_id = $2::uuid
  AND ($3::text IS NULL OR d.doc_type::text = $3::text)
  AND ($4::uuid IS NULL OR d.folder_id = $4::uuid)
  AND ($5::text IS NULL OR d.status::text = $5::text)
  AND (
    $6::boolean
    OR d.owner_id = $7::uuid
    OR (NOT d.is_restricted AND NOT EXISTS (
         SELECT 1 FROM folder_ancestors fa WHERE fa.origin_folder_id=d.folder_id AND fa.is_restricted))
    OR EXISTS (SELECT 1 FROM acl_grants g
         WHERE g.resource_type='document' AND g.resource_id=d.id AND g.permission='read'
           AND g.org_id = $2::uuid
           AND ((g.principal_type='user' AND g.principal_id=$7::uuid)
             OR (g.principal_type='group' AND g.principal_id = ANY($8::uuid[]))))
    OR EXISTS (SELECT 1 FROM folder_ancestors fa
         JOIN acl_grants g ON g.resource_type='folder' AND g.resource_id=fa.ancestor_id AND g.permission='read'
           AND g.org_id = $2::uuid
         WHERE fa.origin_folder_id=d.folder_id
           AND ((g.principal_type='user' AND g.principal_id=$7::uuid)
             OR (g.principal_type='group' AND g.principal_id = ANY($8::uuid[])))))
  ORDER BY d.created_at DESC
  LIMIT $9
`

type ListVisibleDocumentsParams struct {
	TenantID   string   `json:"tenant_id"`
	OrgID      string   `json:"org_id"`
	DocType    *string  `json:"doc_type"`
	FolderID   *string  `json:"folder_id"`
	Status     *string  `json:"status"`
	IsAdmin    bool     `json:"is_admin"`
	UserID     string   `json:"user_id"`
	GroupIds   []string `json:"group_ids"`
	LimitCount int32    `json:"limit_count"`
}

type ListVisibleDocumentsRow struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	OrgID     string             `json:"org_id"`
	FolderID  *string            `json:"folder_id"`
	OwnerID   string             `json:"owner_id"`
	Title     string             `json:"title"`
	DocType   DocumentType       `json:"doc_type"`
	Status    DocumentStatus     `json:"status"`
	Language  *string            `json:"language"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListVisibleDocuments(ctx context.Context, arg ListVisibleDocumentsParams) ([]ListVisibleDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleDocuments,
		arg.TenantID,
		arg.OrgID,
		arg.DocType,
		arg.FolderID,
		arg.Status,
		arg.IsAdmin,
		arg.UserID,
		arg.GroupIds,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleDocumentsRow{}
	for rows.Next() {
		var i ListVisibleDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.FolderID,
			&i.OwnerID,
			&i.Title,
			&i.DocType,
			&i.Status,
			&i.Language,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :execrows
DELETE FROM group_members gm
USING groups g
WHERE gm.group_id = g.id
  AND gm.group_id = $1::uuid AND gm.user_id = $2::uuid
  AND g.tenant_id = $3::uuid AND g.org_id = $4::uuid
`

type RemoveGroupMemberParams struct {
	GroupID  string `json:"group_id"`
	UserID   string `json:"user_id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGroupMember,
		arg.GroupID,
		arg.UserID,
		arg.TenantID,
		arg.OrgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDocumentRestricted = `-- name: SetDocumentRestricted :execrows
UPDATE documents
SET is_restricted = $1::boolean
WHERE id = $2::uuid
  AND tenant_id = $3::uuid AND org_id = $4::uuid
`

type SetDocumentRestrictedParams struct {
	IsRestricted bool   `json:"is_restricted"`
	ID           string `json:"id"`
	TenantID     string `json:"tenant_id"`
	OrgID        string `json:"org_id"`
}

func (q *Queries) SetDocumentRestricted(ctx context.Context, arg SetDocumentRestrictedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDocumentRestricted,
		arg.IsRestricted,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setFolderRestricted = `-- name: SetFolderRestricted :execrows
UPDATE folders
SET is_restricted = $1::boolean
WHERE id = $2::uuid
  AND tenant_id = $3::uuid AND org_id = $4::uuid
`

type SetFolderRestrictedParams struct {
	IsRestricted bool   `json:"is_restricted"`
	ID           string `json:"id"`
	TenantID     string `json:"tenant_id"`
	OrgID        string `json:"org_id"`
}

func (q *Queries) SetFolderRestricted(ctx context.Context, arg SetFolderRestrictedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFolderRestricted,
		arg.IsRestricted,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
