// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acl.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isDocumentVisibleToUser = `-- name: IsDocumentVisibleToUser :one
WITH RECURSIVE folder_chain(folder_id, parent_id, is_restricted) AS (
  SELECT f.id, f.parent_id, f.is_restricted
  FROM folders f JOIN documents d ON d.folder_id = f.id
  WHERE d.id = $4::uuid
    AND d.tenant_id = $5::uuid AND d.org_id = $6::uuid
  UNION ALL
  SELECT pf.id, pf.parent_id, pf.is_restricted
  FROM folders pf JOIN folder_chain fc ON pf.id = fc.parent_id
)
SELECT
  $1::boolean
  OR d.owner_id = $2::uuid
  OR (NOT d.is_restricted AND NOT EXISTS (SELECT 1 FROM folder_chain WHERE is_restricted))
  OR EXISTS (SELECT 1 FROM acl_grants g
       WHERE g.resource_type='document' AND g.resource_id=d.id AND g.permission='read'
         AND ((g.principal_type='user'  AND g.principal_id=$2::uuid)
           OR (g.principal_type='group' AND g.principal_id = ANY($3::uuid[]))))
  OR EXISTS (SELECT 1 FROM acl_grants g
       WHERE g.resource_type='folder' AND g.resource_id IN (SELECT folder_id FROM folder_chain)
         AND g.permission='read'
         AND ((g.principal_type='user'  AND g.principal_id=$2::uuid)
           OR (g.principal_type='group' AND g.principal_id = ANY($3::uuid[])))) AS visible
FROM documents d
WHERE d.id = $4::uuid
  AND d.tenant_id = $5::uuid AND d.org_id = $6::uuid
`

type IsDocumentVisibleToUserParams struct {
	IsAdmin    bool     `json:"is_admin"`
	UserID     string   `json:"user_id"`
	GroupIds   []string `json:"group_ids"`
	DocumentID string   `json:"document_id"`
	TenantID   string   `json:"tenant_id"`
	OrgID      string   `json:"org_id"`
}

func (q *Queries) IsDocumentVisibleToUser(ctx context.Context, arg IsDocumentVisibleToUserParams) (*bool, error) {
	row := q.db.QueryRow(ctx, isDocumentVisibleToUser,
		arg.IsAdmin,
		arg.UserID,
		arg.GroupIds,
		arg.DocumentID,
		arg.TenantID,
		arg.OrgID,
	)
	var visible *bool
	err := row.Scan(&visible)
	return visible, err
}

const listGroupIDsForUser = `-- name: ListGroupIDsForUser :many
SELECT gm.group_id FROM group_members gm JOIN groups g ON g.id = gm.group_id
WHERE gm.user_id = $1::uuid AND g.org_id = $2::uuid
`

type ListGroupIDsForUserParams struct {
	UserID string `json:"user_id"`
	OrgID  string `json:"org_id"`
}

func (q *Queries) ListGroupIDsForUser(ctx context.Context, arg ListGroupIDsForUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGroupIDsForUser, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var group_id string
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleDocuments = `-- name: ListVisibleDocuments :many
WITH RECURSIVE folder_ancestors AS (
  SELECT f.id AS origin_folder_id, f.id AS ancestor_id, f.parent_id, f.is_restricted
  FROM folders f WHERE f.org_id = $2::uuid
  UNION ALL
  SELECT fa.origin_folder_id, pf.id, pf.parent_id, pf.is_restricted
  FROM folders pf JOIN folder_ancestors fa ON pf.id = fa.parent_id
)
SELECT d.id, d.tenant_id, d.org_id, d.folder_id, d.owner_id, d.title,
       d.doc_type, d.status, d.language, d.created_at
FROM documents d
WHERE d.tenant_id = $1::uuid AND d.org_id = $2::uuid
  AND ($3::text IS NULL OR d.doc_type::text = $3::text)
  AND ($4::uuid IS NULL OR d.folder_id = $4::uuid)
  AND ($5::text IS NULL OR d.status::text = $5::text)
  AND (
    $6::boolean
    OR d.owner_id = $7::uuid
    OR (NOT d.is_restricted AND NOT EXISTS (
         SELECT 1 FROM folder_ancestors fa WHERE fa.origin_folder_id=d.folder_id AND fa.is_restricted))
    OR EXISTS (SELECT 1 FROM acl_grants g
         WHERE g.resource_type='document' AND g.resource_id=d.id AND g.permission='read'
           AND ((g.principal_type='user' AND g.principal_id=$7::uuid)
             OR (g.principal_type='group' AND g.principal_id = ANY($8::uuid[]))))
    OR EXISTS (SELECT 1 FROM folder_ancestors fa
         JOIN acl_grants g ON g.resource_type='folder' AND g.resource_id=fa.ancestor_id AND g.permission='read'
         WHERE fa.origin_folder_id=d.folder_id
           AND ((g.principal_type='user' AND g.principal_id=$7::uuid)
             OR (g.principal_type='group' AND g.principal_id = ANY($8::uuid[])))))
  ORDER BY d.created_at DESC
  LIMIT $9
`

type ListVisibleDocumentsParams struct {
	TenantID   string   `json:"tenant_id"`
	OrgID      string   `json:"org_id"`
	DocType    *string  `json:"doc_type"`
	FolderID   *string  `json:"folder_id"`
	Status     *string  `json:"status"`
	IsAdmin    bool     `json:"is_admin"`
	UserID     string   `json:"user_id"`
	GroupIds   []string `json:"group_ids"`
	LimitCount int32    `json:"limit_count"`
}

type ListVisibleDocumentsRow struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	OrgID     string             `json:"org_id"`
	FolderID  *string            `json:"folder_id"`
	OwnerID   string             `json:"owner_id"`
	Title     string             `json:"title"`
	DocType   DocumentType       `json:"doc_type"`
	Status    DocumentStatus     `json:"status"`
	Language  *string            `json:"language"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListVisibleDocuments(ctx context.Context, arg ListVisibleDocumentsParams) ([]ListVisibleDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleDocuments,
		arg.TenantID,
		arg.OrgID,
		arg.DocType,
		arg.FolderID,
		arg.Status,
		arg.IsAdmin,
		arg.UserID,
		arg.GroupIds,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleDocumentsRow{}
	for rows.Next() {
		var i ListVisibleDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.FolderID,
			&i.OwnerID,
			&i.Title,
			&i.DocType,
			&i.Status,
			&i.Language,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
