// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (id, tenant_id, actor_id, entity_type, entity_id, action, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
`

type CreateAuditEventParams struct {
	ID         string  `json:"id"`
	TenantID   string  `json:"tenant_id"`
	ActorID    *string `json:"actor_id"`
	EntityType string  `json:"entity_type"`
	EntityID   string  `json:"entity_id"`
	Action     string  `json:"action"`
	Metadata   []byte  `json:"metadata"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Metadata,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT ae.id, ae.tenant_id, ae.actor_id, ae.entity_type, ae.entity_id, ae.action, ae.metadata, ae.created_at
FROM audit_events ae
WHERE ae.tenant_id = $1
  AND ($2::text IS NULL OR ae.entity_type = $2::text)
  AND ($3::uuid IS NULL OR ae.actor_id = $3::uuid)
  AND ($4::text IS NULL OR ae.action = $4::text)
  AND ($5::uuid IS NULL OR ae.created_at < (SELECT created_at FROM audit_events WHERE id = $5::uuid))
ORDER BY ae.created_at DESC
LIMIT $6
`

type ListAuditEventsParams struct {
	TenantIDArg string  `json:"tenant_id_arg"`
	EntityType  *string `json:"entity_type"`
	ActorID     *string `json:"actor_id"`
	Action      *string `json:"action"`
	CursorID    *string `json:"cursor_id"`
	LimitCount  int32   `json:"limit_count"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.TenantIDArg,
		arg.EntityType,
		arg.ActorID,
		arg.Action,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
