// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :exec
INSERT INTO documents (id, tenant_id, org_id, folder_id, owner_id, title, doc_type, status, language, processing_stage, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
`

type CreateDocumentParams struct {
	ID              string         `json:"id"`
	TenantID        string         `json:"tenant_id"`
	OrgID           string         `json:"org_id"`
	FolderID        *string        `json:"folder_id"`
	OwnerID         string         `json:"owner_id"`
	Title           string         `json:"title"`
	DocType         DocumentType   `json:"doc_type"`
	Status          DocumentStatus `json:"status"`
	Language        *string        `json:"language"`
	ProcessingStage *string        `json:"processing_stage"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.Exec(ctx, createDocument,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
		arg.FolderID,
		arg.OwnerID,
		arg.Title,
		arg.DocType,
		arg.Status,
		arg.Language,
		arg.ProcessingStage,
	)
	return err
}

const createDocumentPage = `-- name: CreateDocumentPage :exec
INSERT INTO document_pages (id, document_id, version_id, page_number, ocr_text, translated_text, confidence, ocr_model, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
`

type CreateDocumentPageParams struct {
	ID             string   `json:"id"`
	DocumentID     string   `json:"document_id"`
	VersionID      string   `json:"version_id"`
	PageNumber     int32    `json:"page_number"`
	OcrText        *string  `json:"ocr_text"`
	TranslatedText *string  `json:"translated_text"`
	Confidence     *float32 `json:"confidence"`
	OcrModel       string   `json:"ocr_model"`
}

func (q *Queries) CreateDocumentPage(ctx context.Context, arg CreateDocumentPageParams) error {
	_, err := q.db.Exec(ctx, createDocumentPage,
		arg.ID,
		arg.DocumentID,
		arg.VersionID,
		arg.PageNumber,
		arg.OcrText,
		arg.TranslatedText,
		arg.Confidence,
		arg.OcrModel,
	)
	return err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :exec
INSERT INTO document_versions (id, document_id, version_number, storage_key, mime_type, file_size, uploaded_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
`

type CreateDocumentVersionParams struct {
	ID            string  `json:"id"`
	DocumentID    string  `json:"document_id"`
	VersionNumber int32   `json:"version_number"`
	StorageKey    string  `json:"storage_key"`
	MimeType      string  `json:"mime_type"`
	FileSize      int64   `json:"file_size"`
	UploadedBy    *string `json:"uploaded_by"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) error {
	_, err := q.db.Exec(ctx, createDocumentVersion,
		arg.ID,
		arg.DocumentID,
		arg.VersionNumber,
		arg.StorageKey,
		arg.MimeType,
		arg.FileSize,
		arg.UploadedBy,
	)
	return err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents
WHERE id = $1 AND tenant_id = $2 AND org_id = $3
`

type DeleteDocumentParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, arg.ID, arg.TenantID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, tenant_id, org_id, folder_id, owner_id, title, doc_type, status, language,
       processing_stage, processing_error,
       suggested_folder_name, suggested_filename, suggestion_confidence, suggestion_create_new,
       created_at
FROM documents
WHERE id = $1 AND tenant_id = $2 AND org_id = $3
`

type GetDocumentByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

type GetDocumentByIDRow struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	OrgID                string             `json:"org_id"`
	FolderID             *string            `json:"folder_id"`
	OwnerID              string             `json:"owner_id"`
	Title                string             `json:"title"`
	DocType              DocumentType       `json:"doc_type"`
	Status               DocumentStatus     `json:"status"`
	Language             *string            `json:"language"`
	ProcessingStage      *string            `json:"processing_stage"`
	ProcessingError      *string            `json:"processing_error"`
	SuggestedFolderName  *string            `json:"suggested_folder_name"`
	SuggestedFilename    *string            `json:"suggested_filename"`
	SuggestionConfidence *float32           `json:"suggestion_confidence"`
	SuggestionCreateNew  *bool              `json:"suggestion_create_new"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (GetDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, arg.ID, arg.TenantID, arg.OrgID)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrgID,
		&i.FolderID,
		&i.OwnerID,
		&i.Title,
		&i.DocType,
		&i.Status,
		&i.Language,
		&i.ProcessingStage,
		&i.ProcessingError,
		&i.SuggestedFolderName,
		&i.SuggestedFilename,
		&i.SuggestionConfidence,
		&i.SuggestionCreateNew,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentMetadata = `-- name: GetDocumentMetadata :many
SELECT m.id, m.document_id, m.key, m.extracted_value, m.corrected_value, m.corrected_by, m.corrected_at, m.created_at
FROM document_metadata m
JOIN documents d ON d.id = m.document_id
WHERE m.document_id = $1 AND d.tenant_id = $2
ORDER BY key ASC
`

type GetDocumentMetadataParams struct {
	DocumentID string `json:"document_id"`
	TenantID   string `json:"tenant_id"`
}

func (q *Queries) GetDocumentMetadata(ctx context.Context, arg GetDocumentMetadataParams) ([]DocumentMetadatum, error) {
	rows, err := q.db.Query(ctx, getDocumentMetadata, arg.DocumentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentMetadatum{}
	for rows.Next() {
		var i DocumentMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Key,
			&i.ExtractedValue,
			&i.CorrectedValue,
			&i.CorrectedBy,
			&i.CorrectedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentPages = `-- name: GetDocumentPages :many
SELECT p.id, p.document_id, p.version_id, p.page_number, p.ocr_text, p.translated_text, p.confidence, p.ocr_model, p.created_at
FROM document_pages p
JOIN documents d ON d.id = p.document_id
WHERE p.document_id = $1 AND d.tenant_id = $2
ORDER BY page_number ASC
`

type GetDocumentPagesParams struct {
	DocumentID string `json:"document_id"`
	TenantID   string `json:"tenant_id"`
}

type GetDocumentPagesRow struct {
	ID             string             `json:"id"`
	DocumentID     string             `json:"document_id"`
	VersionID      string             `json:"version_id"`
	PageNumber     int32              `json:"page_number"`
	OcrText        *string            `json:"ocr_text"`
	TranslatedText *string            `json:"translated_text"`
	Confidence     *float32           `json:"confidence"`
	OcrModel       string             `json:"ocr_model"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDocumentPages(ctx context.Context, arg GetDocumentPagesParams) ([]GetDocumentPagesRow, error) {
	rows, err := q.db.Query(ctx, getDocumentPages, arg.DocumentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentPagesRow{}
	for rows.Next() {
		var i GetDocumentPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.VersionID,
			&i.PageNumber,
			&i.OcrText,
			&i.TranslatedText,
			&i.Confidence,
			&i.OcrModel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentStats = `-- name: GetDocumentStats :one
WITH doc_stats AS (
  SELECT
    COUNT(*) as total_documents,
    COUNT(*) FILTER (WHERE status = 'pending' OR status = 'processing') as pending_documents,
    COUNT(*) FILTER (WHERE status = 'processed' AND created_at >= NOW() - INTERVAL '7 days') as completed_this_week
  FROM documents d
  WHERE d.tenant_id = $1
    AND d.org_id = $2
),
storage_stats AS (
  SELECT COALESCE(SUM(v.file_size), 0)::bigint as storage_used_bytes
  FROM documents d
  JOIN document_versions v ON d.id = v.document_id
  WHERE d.tenant_id = $1
    AND d.org_id = $2
)
SELECT d.total_documents, d.pending_documents, d.completed_this_week, s.storage_used_bytes
FROM doc_stats d, storage_stats s
`

type GetDocumentStatsParams struct {
	TenantIDArg string `json:"tenant_id_arg"`
	OrgIDArg    string `json:"org_id_arg"`
}

type GetDocumentStatsRow struct {
	TotalDocuments    int64 `json:"total_documents"`
	PendingDocuments  int64 `json:"pending_documents"`
	CompletedThisWeek int64 `json:"completed_this_week"`
	StorageUsedBytes  int64 `json:"storage_used_bytes"`
}

func (q *Queries) GetDocumentStats(ctx context.Context, arg GetDocumentStatsParams) (GetDocumentStatsRow, error) {
	row := q.db.QueryRow(ctx, getDocumentStats, arg.TenantIDArg, arg.OrgIDArg)
	var i GetDocumentStatsRow
	err := row.Scan(
		&i.TotalDocuments,
		&i.PendingDocuments,
		&i.CompletedThisWeek,
		&i.StorageUsedBytes,
	)
	return i, err
}

const getDocumentVersions = `-- name: GetDocumentVersions :many
SELECT dv.id, dv.document_id, dv.version_number, dv.storage_key, dv.mime_type, dv.file_size, dv.uploaded_by, dv.created_at
FROM document_versions dv
JOIN documents d ON dv.document_id = d.id
WHERE dv.document_id = $1 AND d.tenant_id = $2
ORDER BY dv.version_number DESC
`

type GetDocumentVersionsParams struct {
	DocumentID string `json:"document_id"`
	TenantID   string `json:"tenant_id"`
}

func (q *Queries) GetDocumentVersions(ctx context.Context, arg GetDocumentVersionsParams) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, getDocumentVersions, arg.DocumentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentVersion{}
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.VersionNumber,
			&i.StorageKey,
			&i.MimeType,
			&i.FileSize,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT d.id, d.tenant_id, d.org_id, d.folder_id, d.owner_id, d.title, d.doc_type, d.status, d.language, d.created_at
FROM documents d
WHERE d.tenant_id = $1
  AND d.org_id = $2
  AND ($3::text IS NULL OR d.doc_type::text = $3::text)
  AND ($4::uuid IS NULL OR d.folder_id = $4::uuid)
  AND ($5::text IS NULL OR d.status::text = $5::text)
  AND ($6::text IS NULL OR d.language = $6::text)
  AND ($7::uuid IS NULL OR d.created_at < (SELECT created_at FROM documents WHERE id = $7::uuid))
ORDER BY d.created_at DESC
LIMIT $8
`

type ListDocumentsParams struct {
	TenantIDArg string  `json:"tenant_id_arg"`
	OrgIDArg    string  `json:"org_id_arg"`
	DocType     *string `json:"doc_type"`
	FolderID    *string `json:"folder_id"`
	Status      *string `json:"status"`
	Language    *string `json:"language"`
	CursorID    *string `json:"cursor_id"`
	LimitCount  int32   `json:"limit_count"`
}

type ListDocumentsRow struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	OrgID     string             `json:"org_id"`
	FolderID  *string            `json:"folder_id"`
	OwnerID   string             `json:"owner_id"`
	Title     string             `json:"title"`
	DocType   DocumentType       `json:"doc_type"`
	Status    DocumentStatus     `json:"status"`
	Language  *string            `json:"language"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.TenantIDArg,
		arg.OrgIDArg,
		arg.DocType,
		arg.FolderID,
		arg.Status,
		arg.Language,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsRow{}
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.FolderID,
			&i.OwnerID,
			&i.Title,
			&i.DocType,
			&i.Status,
			&i.Language,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentMetadata = `-- name: SetDocumentMetadata :exec
INSERT INTO document_metadata (id, document_id, key, extracted_value, corrected_value, corrected_by, corrected_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
ON CONFLICT (document_id, key) DO UPDATE SET
  extracted_value = EXCLUDED.extracted_value,
  corrected_value = EXCLUDED.corrected_value,
  corrected_by = EXCLUDED.corrected_by,
  corrected_at = EXCLUDED.corrected_at
`

type SetDocumentMetadataParams struct {
	ID             string             `json:"id"`
	DocumentID     string             `json:"document_id"`
	Key            string             `json:"key"`
	ExtractedValue *string            `json:"extracted_value"`
	CorrectedValue *string            `json:"corrected_value"`
	CorrectedBy    *string            `json:"corrected_by"`
	CorrectedAt    pgtype.Timestamptz `json:"corrected_at"`
}

func (q *Queries) SetDocumentMetadata(ctx context.Context, arg SetDocumentMetadataParams) error {
	_, err := q.db.Exec(ctx, setDocumentMetadata,
		arg.ID,
		arg.DocumentID,
		arg.Key,
		arg.ExtractedValue,
		arg.CorrectedValue,
		arg.CorrectedBy,
		arg.CorrectedAt,
	)
	return err
}

const updateDocument = `-- name: UpdateDocument :exec
UPDATE documents
SET title = $1, doc_type = $2, status = $3, language = $4, folder_id = $5
WHERE id = $6 AND tenant_id = $7 AND org_id = $8
`

type UpdateDocumentParams struct {
	Title    string         `json:"title"`
	DocType  DocumentType   `json:"doc_type"`
	Status   DocumentStatus `json:"status"`
	Language *string        `json:"language"`
	FolderID *string        `json:"folder_id"`
	ID       string         `json:"id"`
	TenantID string         `json:"tenant_id"`
	OrgID    string         `json:"org_id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error {
	_, err := q.db.Exec(ctx, updateDocument,
		arg.Title,
		arg.DocType,
		arg.Status,
		arg.Language,
		arg.FolderID,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
	)
	return err
}

const updateDocumentMetadataField = `-- name: UpdateDocumentMetadataField :execrows
UPDATE document_metadata m
SET corrected_value = $1, corrected_by = $2, corrected_at = NOW()
FROM documents d
WHERE m.document_id = d.id AND m.document_id = $3 AND m.key = $4 AND d.tenant_id = $5
`

type UpdateDocumentMetadataFieldParams struct {
	CorrectedValue *string `json:"corrected_value"`
	CorrectedBy    *string `json:"corrected_by"`
	DocumentID     string  `json:"document_id"`
	Key            string  `json:"key"`
	TenantID       string  `json:"tenant_id"`
}

func (q *Queries) UpdateDocumentMetadataField(ctx context.Context, arg UpdateDocumentMetadataFieldParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDocumentMetadataField,
		arg.CorrectedValue,
		arg.CorrectedBy,
		arg.DocumentID,
		arg.Key,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocumentProcessingFields = `-- name: UpdateDocumentProcessingFields :exec
UPDATE documents
SET processing_stage = COALESCE($1, processing_stage),
    processing_error = COALESCE($2, processing_error)
WHERE id = $3 AND tenant_id = $4
`

type UpdateDocumentProcessingFieldsParams struct {
	ProcessingStage *string `json:"processing_stage"`
	ProcessingError *string `json:"processing_error"`
	ID              string  `json:"id"`
	TenantID        string  `json:"tenant_id"`
}

func (q *Queries) UpdateDocumentProcessingFields(ctx context.Context, arg UpdateDocumentProcessingFieldsParams) error {
	_, err := q.db.Exec(ctx, updateDocumentProcessingFields,
		arg.ProcessingStage,
		arg.ProcessingError,
		arg.ID,
		arg.TenantID,
	)
	return err
}
