// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package db

import (
	"context"
)

const createFolder = `-- name: CreateFolder :exec
INSERT INTO folders (id, tenant_id, org_id, parent_id, name, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
`

type CreateFolderParams struct {
	ID        string  `json:"id"`
	TenantID  string  `json:"tenant_id"`
	OrgID     string  `json:"org_id"`
	ParentID  *string `json:"parent_id"`
	Name      string  `json:"name"`
	CreatedBy *string `json:"created_by"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) error {
	_, err := q.db.Exec(ctx, createFolder,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
		arg.ParentID,
		arg.Name,
		arg.CreatedBy,
	)
	return err
}

const deleteFolder = `-- name: DeleteFolder :execrows
DELETE FROM folders
WHERE id = $1 AND tenant_id = $2 AND org_id = $3
`

type DeleteFolderParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFolder, arg.ID, arg.TenantID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFolderAncestorIDs = `-- name: GetFolderAncestorIDs :many
WITH RECURSIVE ancestors(id, parent_id, path) AS (
  SELECT f.id, f.parent_id, ARRAY[f.id]
  FROM folders f
  WHERE f.id = $1::uuid
    AND f.tenant_id = $2::uuid AND f.org_id = $3::uuid
  UNION ALL
  SELECT pf.id, pf.parent_id, a.path || pf.id
  FROM folders pf JOIN ancestors a ON pf.id = a.parent_id
  WHERE pf.tenant_id = $2::uuid AND pf.org_id = $3::uuid
    AND NOT pf.id = ANY(a.path) AND array_length(a.path, 1) < 100
)
SELECT id FROM ancestors
`

type GetFolderAncestorIDsParams struct {
	FolderID string `json:"folder_id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

// Returns the folder itself plus all of its ancestors (walking parent_id up to
// the root), cycle-protected via a visited path. Used to detect reparent cycles:
// a folder may not be moved under itself or any of its descendants, which is
// equivalent to rejecting when the moved folder appears among the target
// parent's ancestors (inclusive of the target parent).
func (q *Queries) GetFolderAncestorIDs(ctx context.Context, arg GetFolderAncestorIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getFolderAncestorIDs, arg.FolderID, arg.TenantID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, tenant_id, org_id, parent_id, name, created_by, created_at, is_restricted
FROM folders
WHERE id = $1 AND tenant_id = $2 AND org_id = $3
`

type GetFolderByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) GetFolderByID(ctx context.Context, arg GetFolderByIDParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, arg.ID, arg.TenantID, arg.OrgID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.IsRestricted,
	)
	return i, err
}

const getFolderByParentName = `-- name: GetFolderByParentName :one
SELECT id, tenant_id, org_id, parent_id, name, created_by, created_at, is_restricted
FROM folders
WHERE tenant_id = $1 AND org_id = $2
  AND parent_id IS NOT DISTINCT FROM $3::uuid
  AND lower(name) = lower($4::text)
LIMIT 1
`

type GetFolderByParentNameParams struct {
	TenantID string  `json:"tenant_id"`
	OrgID    string  `json:"org_id"`
	ParentID *string `json:"parent_id"`
	Name     string  `json:"name"`
}

// Finds a folder by its (tenant, org, parent, name) tuple. A NULL parent_id
// matches root-level folders. Name matching is case-insensitive to mirror the
// unique-name indexes (lower(name)).
func (q *Queries) GetFolderByParentName(ctx context.Context, arg GetFolderByParentNameParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByParentName,
		arg.TenantID,
		arg.OrgID,
		arg.ParentID,
		arg.Name,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.IsRestricted,
	)
	return i, err
}

const getFolderSubtreeHeight = `-- name: GetFolderSubtreeHeight :one
WITH RECURSIVE subtree(id, path, depth) AS (
  SELECT f.id, ARRAY[f.id], 1
  FROM folders f
  WHERE f.id = $1::uuid
    AND f.tenant_id = $2::uuid AND f.org_id = $3::uuid
  UNION ALL
  SELECT cf.id, s.path || cf.id, s.depth + 1
  FROM folders cf JOIN subtree s ON cf.parent_id = s.id
  WHERE cf.tenant_id = $2::uuid AND cf.org_id = $3::uuid
    AND NOT cf.id = ANY(s.path) AND array_length(s.path, 1) < 100
)
SELECT COALESCE(MAX(depth), 0)::int AS height FROM subtree
`

type GetFolderSubtreeHeightParams struct {
	FolderID string `json:"folder_id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

// Returns the height of the subtree rooted at folder_id, i.e. the number of
// folder levels from the folder itself down to its deepest descendant. The
// folder alone is height 1. Used as a soft depth guard so a reparent that would
// push the moved subtree's deepest leaf past the cap is rejected. Cycle-protected
// with a path accumulator and a depth cap mirroring the other recursive queries.
func (q *Queries) GetFolderSubtreeHeight(ctx context.Context, arg GetFolderSubtreeHeightParams) (int32, error) {
	row := q.db.QueryRow(ctx, getFolderSubtreeHeight, arg.FolderID, arg.TenantID, arg.OrgID)
	var height int32
	err := row.Scan(&height)
	return height, err
}

const listAllFolders = `-- name: ListAllFolders :many
SELECT id, tenant_id, org_id, parent_id, name, created_by, created_at, is_restricted
FROM folders
WHERE tenant_id = $1 AND org_id = $2
ORDER BY name ASC
`

type ListAllFoldersParams struct {
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) ListAllFolders(ctx context.Context, arg ListAllFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listAllFolders, arg.TenantID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.IsRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByParent = `-- name: ListFoldersByParent :many
SELECT id, tenant_id, org_id, parent_id, name, created_by, created_at, is_restricted
FROM folders
WHERE tenant_id = $1 AND org_id = $2 AND parent_id = $3
ORDER BY name ASC
`

type ListFoldersByParentParams struct {
	TenantID string  `json:"tenant_id"`
	OrgID    string  `json:"org_id"`
	ParentID *string `json:"parent_id"`
}

func (q *Queries) ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByParent, arg.TenantID, arg.OrgID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.IsRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFolders = `-- name: ListRootFolders :many
SELECT id, tenant_id, org_id, parent_id, name, created_by, created_at, is_restricted
FROM folders
WHERE tenant_id = $1 AND org_id = $2 AND parent_id IS NULL
ORDER BY name ASC
`

type ListRootFoldersParams struct {
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) ListRootFolders(ctx context.Context, arg ListRootFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listRootFolders, arg.TenantID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.IsRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFolder = `-- name: MoveFolder :execrows
WITH RECURSIVE descendants(descendant_id, path) AS (
  SELECT f.id, ARRAY[f.id]
  FROM folders f
  WHERE f.id = $2::uuid
    AND f.tenant_id = $3::uuid AND f.org_id = $4::uuid
  UNION ALL
  SELECT cf.id, d.path || cf.id
  FROM folders cf JOIN descendants d ON cf.parent_id = d.descendant_id
  WHERE cf.tenant_id = $3::uuid AND cf.org_id = $4::uuid
    AND NOT cf.id = ANY(d.path) AND array_length(d.path, 1) < 100
)
UPDATE folders
SET parent_id = $1::uuid
WHERE id = $2::uuid
  AND tenant_id = $3::uuid AND org_id = $4::uuid
  AND (
    $1::uuid IS NULL
    OR (
      $1::uuid <> id
      AND $1::uuid NOT IN (SELECT descendant_id FROM descendants)
    )
  )
`

type MoveFolderParams struct {
	NewParent *string `json:"new_parent"`
	ID        string  `json:"id"`
	TenantID  string  `json:"tenant_id"`
	OrgID     string  `json:"org_id"`
}

// Reparents a folder while preserving its name. A NULL new_parent moves the
// folder to root. The cycle check is performed atomically inside this single
// UPDATE so two concurrent opposite reparents cannot each pass a separate check
// and then both write a cycle: the update only succeeds when the new parent is
// neither the folder itself nor any of its descendants. Descendants are gathered
// by a recursive CTE seeded at the folder being moved, cycle-protected with a
// path accumulator and a depth cap mirroring the other recursive queries. A
// 0 rows-affected result signals a rejected (cycle/invalid-parent) move.
func (q *Queries) MoveFolder(ctx context.Context, arg MoveFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveFolder,
		arg.NewParent,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFolder = `-- name: UpdateFolder :exec
UPDATE folders
SET name = $1, parent_id = $2
WHERE id = $3 AND tenant_id = $4 AND org_id = $5
`

type UpdateFolderParams struct {
	Name     string  `json:"name"`
	ParentID *string `json:"parent_id"`
	ID       string  `json:"id"`
	TenantID string  `json:"tenant_id"`
	OrgID    string  `json:"org_id"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) error {
	_, err := q.db.Exec(ctx, updateFolder,
		arg.Name,
		arg.ParentID,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
	)
	return err
}
