// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package db

import (
	"context"
)

const createFolder = `-- name: CreateFolder :exec
INSERT INTO folders (id, tenant_id, org_id, parent_id, name, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
`

type CreateFolderParams struct {
	ID        string  `json:"id"`
	TenantID  string  `json:"tenant_id"`
	OrgID     string  `json:"org_id"`
	ParentID  *string `json:"parent_id"`
	Name      string  `json:"name"`
	CreatedBy *string `json:"created_by"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) error {
	_, err := q.db.Exec(ctx, createFolder,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
		arg.ParentID,
		arg.Name,
		arg.CreatedBy,
	)
	return err
}

const deleteFolder = `-- name: DeleteFolder :execrows
DELETE FROM folders
WHERE id = $1 AND tenant_id = $2 AND org_id = $3
`

type DeleteFolderParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFolder, arg.ID, arg.TenantID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, tenant_id, org_id, parent_id, name, created_by, created_at
FROM folders
WHERE id = $1 AND tenant_id = $2 AND org_id = $3
`

type GetFolderByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) GetFolderByID(ctx context.Context, arg GetFolderByIDParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, arg.ID, arg.TenantID, arg.OrgID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAllFolders = `-- name: ListAllFolders :many
SELECT id, tenant_id, org_id, parent_id, name, created_by, created_at
FROM folders
WHERE tenant_id = $1 AND org_id = $2
ORDER BY name ASC
`

type ListAllFoldersParams struct {
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) ListAllFolders(ctx context.Context, arg ListAllFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listAllFolders, arg.TenantID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByParent = `-- name: ListFoldersByParent :many
SELECT id, tenant_id, org_id, parent_id, name, created_by, created_at
FROM folders
WHERE tenant_id = $1 AND org_id = $2 AND parent_id = $3
ORDER BY name ASC
`

type ListFoldersByParentParams struct {
	TenantID string  `json:"tenant_id"`
	OrgID    string  `json:"org_id"`
	ParentID *string `json:"parent_id"`
}

func (q *Queries) ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByParent, arg.TenantID, arg.OrgID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFolders = `-- name: ListRootFolders :many
SELECT id, tenant_id, org_id, parent_id, name, created_by, created_at
FROM folders
WHERE tenant_id = $1 AND org_id = $2 AND parent_id IS NULL
ORDER BY name ASC
`

type ListRootFoldersParams struct {
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) ListRootFolders(ctx context.Context, arg ListRootFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listRootFolders, arg.TenantID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolder = `-- name: UpdateFolder :exec
UPDATE folders
SET name = $1, parent_id = $2
WHERE id = $3 AND tenant_id = $4 AND org_id = $5
`

type UpdateFolderParams struct {
	Name     string  `json:"name"`
	ParentID *string `json:"parent_id"`
	ID       string  `json:"id"`
	TenantID string  `json:"tenant_id"`
	OrgID    string  `json:"org_id"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) error {
	_, err := q.db.Exec(ctx, updateFolder,
		arg.Name,
		arg.ParentID,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
	)
	return err
}
