// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (id, tenant_id, name, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateOrganizationParams struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.Exec(ctx, createOrganization,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name, plan, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateTenantParams struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Plan      string             `json:"plan"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Plan,
		arg.CreatedAt,
	)
	return err
}
