// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (id, user_id, org_id, role, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMembershipParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	OrgID     string             `json:"org_id"`
	Role      MembershipRole     `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership,
		arg.ID,
		arg.UserID,
		arg.OrgID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT m.id AS membership_id, m.user_id, m.org_id, u.email, u.display_name, m.role, m.created_at
FROM memberships m
JOIN users u ON u.id = m.user_id
JOIN organizations o ON o.id = m.org_id
WHERE o.tenant_id = $1 AND m.id = $2
`

type GetMembershipByIDParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

type GetMembershipByIDRow struct {
	MembershipID string             `json:"membership_id"`
	UserID       string             `json:"user_id"`
	OrgID        string             `json:"org_id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	Role         MembershipRole     `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (GetMembershipByIDRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, arg.TenantID, arg.ID)
	var i GetMembershipByIDRow
	err := row.Scan(
		&i.MembershipID,
		&i.UserID,
		&i.OrgID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getPrimaryMembershipByUserID = `-- name: GetPrimaryMembershipByUserID :one
SELECT org_id, role
FROM memberships
WHERE user_id = $1
ORDER BY created_at ASC
LIMIT 1
`

type GetPrimaryMembershipByUserIDParams struct {
	UserID string `json:"user_id"`
}

type GetPrimaryMembershipByUserIDRow struct {
	OrgID string         `json:"org_id"`
	Role  MembershipRole `json:"role"`
}

func (q *Queries) GetPrimaryMembershipByUserID(ctx context.Context, arg GetPrimaryMembershipByUserIDParams) (GetPrimaryMembershipByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getPrimaryMembershipByUserID, arg.UserID)
	var i GetPrimaryMembershipByUserIDRow
	err := row.Scan(&i.OrgID, &i.Role)
	return i, err
}

const listMembershipsByOrg = `-- name: ListMembershipsByOrg :many
SELECT m.id AS membership_id, m.user_id, m.org_id, u.email, u.display_name, m.role, m.created_at
FROM memberships m
JOIN users u ON u.id = m.user_id
JOIN organizations o ON o.id = m.org_id
WHERE o.tenant_id = $1 AND m.org_id = $2
ORDER BY m.created_at ASC
`

type ListMembershipsByOrgParams struct {
	TenantID string `json:"tenant_id"`
	OrgID    string `json:"org_id"`
}

type ListMembershipsByOrgRow struct {
	MembershipID string             `json:"membership_id"`
	UserID       string             `json:"user_id"`
	OrgID        string             `json:"org_id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	Role         MembershipRole     `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMembershipsByOrg(ctx context.Context, arg ListMembershipsByOrgParams) ([]ListMembershipsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByOrg, arg.TenantID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByOrgRow{}
	for rows.Next() {
		var i ListMembershipsByOrgRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.UserID,
			&i.OrgID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByTenant = `-- name: ListMembershipsByTenant :many
SELECT m.id AS membership_id, m.user_id, m.org_id, u.email, u.display_name, m.role, m.created_at
FROM memberships m
JOIN users u ON u.id = m.user_id
JOIN organizations o ON o.id = m.org_id
WHERE o.tenant_id = $1
ORDER BY m.created_at ASC
`

type ListMembershipsByTenantParams struct {
	TenantID string `json:"tenant_id"`
}

type ListMembershipsByTenantRow struct {
	MembershipID string             `json:"membership_id"`
	UserID       string             `json:"user_id"`
	OrgID        string             `json:"org_id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	Role         MembershipRole     `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMembershipsByTenant(ctx context.Context, arg ListMembershipsByTenantParams) ([]ListMembershipsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByTenant, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByTenantRow{}
	for rows.Next() {
		var i ListMembershipsByTenantRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.UserID,
			&i.OrgID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :execrows
UPDATE memberships
SET role = $1
WHERE id = $2
`

type UpdateMembershipRoleParams struct {
	Role MembershipRole `json:"role"`
	ID   string         `json:"id"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMembershipRole, arg.Role, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
