// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AclPermission string

const (
	AclPermissionRead   AclPermission = "read"
	AclPermissionWrite  AclPermission = "write"
	AclPermissionDelete AclPermission = "delete"
)

func (e *AclPermission) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AclPermission(s)
	case string:
		*e = AclPermission(s)
	default:
		return fmt.Errorf("unsupported scan type for AclPermission: %T", src)
	}
	return nil
}

type NullAclPermission struct {
	AclPermission AclPermission `json:"acl_permission"`
	Valid         bool          `json:"valid"` // Valid is true if AclPermission is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAclPermission) Scan(value interface{}) error {
	if value == nil {
		ns.AclPermission, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AclPermission.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAclPermission) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AclPermission), nil
}

type AclPrincipalType string

const (
	AclPrincipalTypeUser  AclPrincipalType = "user"
	AclPrincipalTypeGroup AclPrincipalType = "group"
)

func (e *AclPrincipalType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AclPrincipalType(s)
	case string:
		*e = AclPrincipalType(s)
	default:
		return fmt.Errorf("unsupported scan type for AclPrincipalType: %T", src)
	}
	return nil
}

type NullAclPrincipalType struct {
	AclPrincipalType AclPrincipalType `json:"acl_principal_type"`
	Valid            bool             `json:"valid"` // Valid is true if AclPrincipalType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAclPrincipalType) Scan(value interface{}) error {
	if value == nil {
		ns.AclPrincipalType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AclPrincipalType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAclPrincipalType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AclPrincipalType), nil
}

type AclResourceType string

const (
	AclResourceTypeDocument AclResourceType = "document"
	AclResourceTypeFolder   AclResourceType = "folder"
)

func (e *AclResourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AclResourceType(s)
	case string:
		*e = AclResourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for AclResourceType: %T", src)
	}
	return nil
}

type NullAclResourceType struct {
	AclResourceType AclResourceType `json:"acl_resource_type"`
	Valid           bool            `json:"valid"` // Valid is true if AclResourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAclResourceType) Scan(value interface{}) error {
	if value == nil {
		ns.AclResourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AclResourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAclResourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AclResourceType), nil
}

type DocumentStatus string

const (
	DocumentStatusPending    DocumentStatus = "pending"
	DocumentStatusProcessing DocumentStatus = "processing"
	DocumentStatusProcessed  DocumentStatus = "processed"
	DocumentStatusFailed     DocumentStatus = "failed"
)

func (e *DocumentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentStatus(s)
	case string:
		*e = DocumentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentStatus: %T", src)
	}
	return nil
}

type NullDocumentStatus struct {
	DocumentStatus DocumentStatus `json:"document_status"`
	Valid          bool           `json:"valid"` // Valid is true if DocumentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentStatus), nil
}

type DocumentType string

const (
	DocumentTypeInvoice  DocumentType = "invoice"
	DocumentTypeContract DocumentType = "contract"
	DocumentTypeIdentity DocumentType = "identity"
	DocumentTypeWarranty DocumentType = "warranty"
	DocumentTypeReceipt  DocumentType = "receipt"
	DocumentTypeOther    DocumentType = "other"
)

func (e *DocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentType(s)
	case string:
		*e = DocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentType: %T", src)
	}
	return nil
}

type NullDocumentType struct {
	DocumentType DocumentType `json:"document_type"`
	Valid        bool         `json:"valid"` // Valid is true if DocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentType), nil
}

type MembershipRole string

const (
	MembershipRoleOwner  MembershipRole = "owner"
	MembershipRoleAdmin  MembershipRole = "admin"
	MembershipRoleMember MembershipRole = "member"
	MembershipRoleViewer MembershipRole = "viewer"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type ReminderEventStatus string

const (
	ReminderEventStatusPending ReminderEventStatus = "pending"
	ReminderEventStatusSent    ReminderEventStatus = "sent"
	ReminderEventStatusFailed  ReminderEventStatus = "failed"
	ReminderEventStatusSnoozed ReminderEventStatus = "snoozed"
)

func (e *ReminderEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReminderEventStatus(s)
	case string:
		*e = ReminderEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReminderEventStatus: %T", src)
	}
	return nil
}

type NullReminderEventStatus struct {
	ReminderEventStatus ReminderEventStatus `json:"reminder_event_status"`
	Valid               bool                `json:"valid"` // Valid is true if ReminderEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReminderEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReminderEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReminderEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReminderEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReminderEventStatus), nil
}

type ReminderRuleSource string

const (
	ReminderRuleSourceAuto   ReminderRuleSource = "auto"
	ReminderRuleSourceManual ReminderRuleSource = "manual"
)

func (e *ReminderRuleSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReminderRuleSource(s)
	case string:
		*e = ReminderRuleSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ReminderRuleSource: %T", src)
	}
	return nil
}

type NullReminderRuleSource struct {
	ReminderRuleSource ReminderRuleSource `json:"reminder_rule_source"`
	Valid              bool               `json:"valid"` // Valid is true if ReminderRuleSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReminderRuleSource) Scan(value interface{}) error {
	if value == nil {
		ns.ReminderRuleSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReminderRuleSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReminderRuleSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReminderRuleSource), nil
}

type AclGrant struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	OrgID         string             `json:"org_id"`
	ResourceType  AclResourceType    `json:"resource_type"`
	ResourceID    string             `json:"resource_id"`
	PrincipalType AclPrincipalType   `json:"principal_type"`
	PrincipalID   string             `json:"principal_id"`
	Permission    AclPermission      `json:"permission"`
	GrantedBy     *string            `json:"granted_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuditEvent struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	ActorID    *string            `json:"actor_id"`
	EntityType string             `json:"entity_type"`
	EntityID   string             `json:"entity_id"`
	Action     string             `json:"action"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Casbin RBAC policy table
type CasbinRule struct {
	ID    int64  `json:"id"`
	Ptype string `json:"ptype"`
	// Subject or user/role binding source
	V0 string `json:"v0"`
	// Tenant/domain
	V1 string `json:"v1"`
	// Object or role binding target/domain field
	V2 string `json:"v2"`
	// Action
	V3 string `json:"v3"`
	V4 string `json:"v4"`
	V5 string `json:"v5"`
}

type Document struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	OrgID                string             `json:"org_id"`
	FolderID             *string            `json:"folder_id"`
	OwnerID              string             `json:"owner_id"`
	Title                string             `json:"title"`
	DocType              DocumentType       `json:"doc_type"`
	Status               DocumentStatus     `json:"status"`
	Language             *string            `json:"language"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ProcessingStage      *string            `json:"processing_stage"`
	ProcessingError      *string            `json:"processing_error"`
	SuggestedFolderName  *string            `json:"suggested_folder_name"`
	SuggestedFilename    *string            `json:"suggested_filename"`
	SuggestionConfidence *float32           `json:"suggestion_confidence"`
	SuggestionCreateNew  *bool              `json:"suggestion_create_new"`
	IsRestricted         bool               `json:"is_restricted"`
}

type DocumentMetadatum struct {
	ID             string             `json:"id"`
	DocumentID     string             `json:"document_id"`
	Key            string             `json:"key"`
	ExtractedValue *string            `json:"extracted_value"`
	CorrectedValue *string            `json:"corrected_value"`
	CorrectedBy    *string            `json:"corrected_by"`
	CorrectedAt    pgtype.Timestamptz `json:"corrected_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DocumentPage struct {
	ID             string             `json:"id"`
	DocumentID     string             `json:"document_id"`
	VersionID      string             `json:"version_id"`
	PageNumber     int32              `json:"page_number"`
	OcrText        *string            `json:"ocr_text"`
	Confidence     *float32           `json:"confidence"`
	OcrModel       string             `json:"ocr_model"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TranslatedText *string            `json:"translated_text"`
}

type DocumentTag struct {
	DocumentID string             `json:"document_id"`
	TagID      string             `json:"tag_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type DocumentVersion struct {
	ID            string             `json:"id"`
	DocumentID    string             `json:"document_id"`
	VersionNumber int32              `json:"version_number"`
	StorageKey    string             `json:"storage_key"`
	MimeType      string             `json:"mime_type"`
	FileSize      int64              `json:"file_size"`
	UploadedBy    *string            `json:"uploaded_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ExtractedTextChunk struct {
	ID         string             `json:"id"`
	DocumentID string             `json:"document_id"`
	PageID     string             `json:"page_id"`
	ChunkIndex int32              `json:"chunk_index"`
	ChunkText  string             `json:"chunk_text"`
	Embedding  *string            `json:"embedding"`
	ChunkTsv   interface{}        `json:"chunk_tsv"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Folder struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	OrgID        string             `json:"org_id"`
	ParentID     *string            `json:"parent_id"`
	Name         string             `json:"name"`
	CreatedBy    *string            `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	IsRestricted bool               `json:"is_restricted"`
	IndexContent *string            `json:"index_content"`
}

type Group struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	OrgID     string             `json:"org_id"`
	Name      string             `json:"name"`
	CreatedBy *string            `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GroupMember struct {
	GroupID   string             `json:"group_id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	OrgID     string             `json:"org_id"`
	Role      MembershipRole     `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      *string            `json:"body"`
	Link      *string            `json:"link"`
	Status    string             `json:"status"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type Organization struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReminderEvent struct {
	ID           string              `json:"id"`
	RuleID       string              `json:"rule_id"`
	ScheduledAt  pgtype.Timestamptz  `json:"scheduled_at"`
	SentAt       pgtype.Timestamptz  `json:"sent_at"`
	Channel      string              `json:"channel"`
	Status       ReminderEventStatus `json:"status"`
	ErrorMessage *string             `json:"error_message"`
	CreatedAt    pgtype.Timestamptz  `json:"created_at"`
}

type ReminderRule struct {
	ID               string             `json:"id"`
	DocumentID       string             `json:"document_id"`
	TenantID         string             `json:"tenant_id"`
	RuleType         string             `json:"rule_type"`
	TriggerDate      pgtype.Date        `json:"trigger_date"`
	NotifyDaysBefore []int32            `json:"notify_days_before"`
	Source           ReminderRuleSource `json:"source"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Plan      string             `json:"plan"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Locale      string             `json:"locale"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	// bcrypt hash of user password (cost factor 12)
	PasswordHash *string `json:"password_hash"`
	// Whether user has verified their email address
	EmailVerified bool `json:"email_verified"`
	// Timestamp of last successful login
	LastLoginAt *time.Time `json:"last_login_at"`
	// Counter for failed login attempts (reset on successful login)
	FailedLoginAttempts int32 `json:"failed_login_attempts"`
	// Timestamp until which account is locked due to too many failed attempts
	LockedUntil *time.Time `json:"locked_until"`
}
