// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (id, tenant_id, user_id, type, title, body, link, status, metadata, created_at, read_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), $10)
`

type CreateNotificationParams struct {
	ID       string             `json:"id"`
	TenantID string             `json:"tenant_id"`
	UserID   string             `json:"user_id"`
	Type     string             `json:"type"`
	Title    string             `json:"title"`
	Body     *string            `json:"body"`
	Link     *string            `json:"link"`
	Status   string             `json:"status"`
	Metadata []byte             `json:"metadata"`
	ReadAt   pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.Status,
		arg.Metadata,
		arg.ReadAt,
	)
	return err
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*)
FROM notifications
WHERE tenant_id = $1 AND user_id = $2 AND status = 'unread'
`

type GetUnreadNotificationCountParams struct {
	TenantID string `json:"tenant_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, arg GetUnreadNotificationCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, arg.TenantID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.tenant_id, n.user_id, n.type, n.title, n.body, n.link, n.status, n.metadata, n.created_at, n.read_at
FROM notifications n
WHERE n.tenant_id = $1
  AND n.user_id = $2
  AND ($3::text IS NULL OR n.status = $3::text)
  AND ($4::uuid IS NULL OR n.created_at < (SELECT created_at FROM notifications WHERE id = $4::uuid))
ORDER BY n.created_at DESC
LIMIT $5
`

type ListNotificationsParams struct {
	TenantIDArg string  `json:"tenant_id_arg"`
	UserIDArg   string  `json:"user_id_arg"`
	Status      *string `json:"status"`
	CursorID    *string `json:"cursor_id"`
	LimitCount  int32   `json:"limit_count"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.TenantIDArg,
		arg.UserIDArg,
		arg.Status,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET status = 'read', read_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND user_id = $3
`

type MarkNotificationReadParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
