// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddTagToDocument(ctx context.Context, arg AddTagToDocumentParams) error
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	CreateDocument(ctx context.Context, arg CreateDocumentParams) error
	CreateDocumentPage(ctx context.Context, arg CreateDocumentPageParams) error
	CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) error
	CreateFolder(ctx context.Context, arg CreateFolderParams) error
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	CreateNotification(ctx context.Context, arg CreateNotificationParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error
	CreateReminderEvent(ctx context.Context, arg CreateReminderEventParams) error
	CreateReminderRule(ctx context.Context, arg CreateReminderRuleParams) error
	CreateTag(ctx context.Context, arg CreateTagParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (int64, error)
	DeleteFolder(ctx context.Context, arg DeleteFolderParams) (int64, error)
	DeleteReminderRule(ctx context.Context, arg DeleteReminderRuleParams) (int64, error)
	DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error)
	FindUserByEmail(ctx context.Context, arg FindUserByEmailParams) (FindUserByEmailRow, error)
	FindUserByID(ctx context.Context, arg FindUserByIDParams) (FindUserByIDRow, error)
	GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (GetDocumentByIDRow, error)
	GetDocumentMetadata(ctx context.Context, arg GetDocumentMetadataParams) ([]DocumentMetadatum, error)
	GetDocumentPages(ctx context.Context, arg GetDocumentPagesParams) ([]GetDocumentPagesRow, error)
	GetDocumentStats(ctx context.Context, arg GetDocumentStatsParams) (GetDocumentStatsRow, error)
	GetDocumentTags(ctx context.Context, arg GetDocumentTagsParams) ([]Tag, error)
	GetDocumentVersions(ctx context.Context, arg GetDocumentVersionsParams) ([]DocumentVersion, error)
	GetFolderByID(ctx context.Context, arg GetFolderByIDParams) (Folder, error)
	GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (GetMembershipByIDRow, error)
	GetPendingReminderEvents(ctx context.Context, arg GetPendingReminderEventsParams) ([]ReminderEvent, error)
	GetPrimaryMembershipByUserID(ctx context.Context, arg GetPrimaryMembershipByUserIDParams) (GetPrimaryMembershipByUserIDRow, error)
	GetReminderRuleByID(ctx context.Context, arg GetReminderRuleByIDParams) (ReminderRule, error)
	GetReminderRulesByDocument(ctx context.Context, arg GetReminderRulesByDocumentParams) ([]ReminderRule, error)
	GetTagByID(ctx context.Context, arg GetTagByIDParams) (Tag, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error)
	GetUnreadNotificationCount(ctx context.Context, arg GetUnreadNotificationCountParams) (int64, error)
	IsDocumentVisibleToUser(ctx context.Context, arg IsDocumentVisibleToUserParams) (*bool, error)
	IsEmailTakenByOther(ctx context.Context, arg IsEmailTakenByOtherParams) (bool, error)
	ListActiveReminderRulesByTenant(ctx context.Context, arg ListActiveReminderRulesByTenantParams) ([]ReminderRule, error)
	ListAllFolders(ctx context.Context, arg ListAllFoldersParams) ([]Folder, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error)
	ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error)
	ListGroupIDsForUser(ctx context.Context, arg ListGroupIDsForUserParams) ([]string, error)
	ListMembershipsByOrg(ctx context.Context, arg ListMembershipsByOrgParams) ([]ListMembershipsByOrgRow, error)
	ListMembershipsByTenant(ctx context.Context, arg ListMembershipsByTenantParams) ([]ListMembershipsByTenantRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListReminderRulesByTenant(ctx context.Context, arg ListReminderRulesByTenantParams) ([]ReminderRule, error)
	ListRootFolders(ctx context.Context, arg ListRootFoldersParams) ([]Folder, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	ListUpcomingReminderRules(ctx context.Context, arg ListUpcomingReminderRulesParams) ([]ReminderRule, error)
	ListVisibleDocuments(ctx context.Context, arg ListVisibleDocumentsParams) ([]ListVisibleDocumentsRow, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	RemoveTagFromDocument(ctx context.Context, arg RemoveTagFromDocumentParams) error
	SearchDocumentChunks(ctx context.Context, arg SearchDocumentChunksParams) ([]SearchDocumentChunksRow, error)
	SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error)
	SetDocumentMetadata(ctx context.Context, arg SetDocumentMetadataParams) error
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error
	UpdateDocumentMetadataField(ctx context.Context, arg UpdateDocumentMetadataFieldParams) (int64, error)
	UpdateDocumentProcessingFields(ctx context.Context, arg UpdateDocumentProcessingFieldsParams) error
	UpdateFolder(ctx context.Context, arg UpdateFolderParams) error
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (int64, error)
	UpdateReminderEvent(ctx context.Context, arg UpdateReminderEventParams) error
	UpdateReminderRule(ctx context.Context, arg UpdateReminderRuleParams) error
	UpdateSuccessfulLoginMetadata(ctx context.Context, arg UpdateSuccessfulLoginMetadataParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserFailedLogin(ctx context.Context, arg UpdateUserFailedLoginParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
