// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReminderEvent = `-- name: CreateReminderEvent :exec
INSERT INTO reminder_events (id, rule_id, scheduled_at, sent_at, channel, status, error_message, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
`

type CreateReminderEventParams struct {
	ID           string              `json:"id"`
	RuleID       string              `json:"rule_id"`
	ScheduledAt  pgtype.Timestamptz  `json:"scheduled_at"`
	SentAt       pgtype.Timestamptz  `json:"sent_at"`
	Channel      string              `json:"channel"`
	Status       ReminderEventStatus `json:"status"`
	ErrorMessage *string             `json:"error_message"`
}

func (q *Queries) CreateReminderEvent(ctx context.Context, arg CreateReminderEventParams) error {
	_, err := q.db.Exec(ctx, createReminderEvent,
		arg.ID,
		arg.RuleID,
		arg.ScheduledAt,
		arg.SentAt,
		arg.Channel,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}

const createReminderRule = `-- name: CreateReminderRule :exec
INSERT INTO reminder_rules (id, document_id, tenant_id, rule_type, trigger_date, notify_days_before, source, active, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
`

type CreateReminderRuleParams struct {
	ID               string             `json:"id"`
	DocumentID       string             `json:"document_id"`
	TenantID         string             `json:"tenant_id"`
	RuleType         string             `json:"rule_type"`
	TriggerDate      pgtype.Date        `json:"trigger_date"`
	NotifyDaysBefore []int32            `json:"notify_days_before"`
	Source           ReminderRuleSource `json:"source"`
	Active           bool               `json:"active"`
}

func (q *Queries) CreateReminderRule(ctx context.Context, arg CreateReminderRuleParams) error {
	_, err := q.db.Exec(ctx, createReminderRule,
		arg.ID,
		arg.DocumentID,
		arg.TenantID,
		arg.RuleType,
		arg.TriggerDate,
		arg.NotifyDaysBefore,
		arg.Source,
		arg.Active,
	)
	return err
}

const deleteReminderRule = `-- name: DeleteReminderRule :execrows
DELETE FROM reminder_rules
WHERE id = $1 AND tenant_id = $2
`

type DeleteReminderRuleParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) DeleteReminderRule(ctx context.Context, arg DeleteReminderRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReminderRule, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingReminderEvents = `-- name: GetPendingReminderEvents :many
SELECT id, rule_id, scheduled_at, sent_at, channel, status, error_message, created_at
FROM reminder_events
WHERE status = 'pending' AND scheduled_at <= $1
ORDER BY scheduled_at ASC
`

type GetPendingReminderEventsParams struct {
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) GetPendingReminderEvents(ctx context.Context, arg GetPendingReminderEventsParams) ([]ReminderEvent, error) {
	rows, err := q.db.Query(ctx, getPendingReminderEvents, arg.ScheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReminderEvent{}
	for rows.Next() {
		var i ReminderEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.ScheduledAt,
			&i.SentAt,
			&i.Channel,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReminderRuleByID = `-- name: GetReminderRuleByID :one
SELECT id, document_id, tenant_id, rule_type, trigger_date, notify_days_before, source, active, created_at
FROM reminder_rules
WHERE id = $1 AND tenant_id = $2
`

type GetReminderRuleByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetReminderRuleByID(ctx context.Context, arg GetReminderRuleByIDParams) (ReminderRule, error) {
	row := q.db.QueryRow(ctx, getReminderRuleByID, arg.ID, arg.TenantID)
	var i ReminderRule
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.TenantID,
		&i.RuleType,
		&i.TriggerDate,
		&i.NotifyDaysBefore,
		&i.Source,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getReminderRulesByDocument = `-- name: GetReminderRulesByDocument :many
SELECT id, document_id, tenant_id, rule_type, trigger_date, notify_days_before, source, active, created_at
FROM reminder_rules
WHERE document_id = $1 AND tenant_id = $2
ORDER BY trigger_date ASC
`

type GetReminderRulesByDocumentParams struct {
	DocumentID string `json:"document_id"`
	TenantID   string `json:"tenant_id"`
}

func (q *Queries) GetReminderRulesByDocument(ctx context.Context, arg GetReminderRulesByDocumentParams) ([]ReminderRule, error) {
	rows, err := q.db.Query(ctx, getReminderRulesByDocument, arg.DocumentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReminderRule{}
	for rows.Next() {
		var i ReminderRule
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.TenantID,
			&i.RuleType,
			&i.TriggerDate,
			&i.NotifyDaysBefore,
			&i.Source,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveReminderRulesByTenant = `-- name: ListActiveReminderRulesByTenant :many
SELECT id, document_id, tenant_id, rule_type, trigger_date, notify_days_before, source, active, created_at
FROM reminder_rules
WHERE tenant_id = $1 AND active = true
ORDER BY trigger_date ASC, created_at DESC
`

type ListActiveReminderRulesByTenantParams struct {
	TenantID string `json:"tenant_id"`
}

func (q *Queries) ListActiveReminderRulesByTenant(ctx context.Context, arg ListActiveReminderRulesByTenantParams) ([]ReminderRule, error) {
	rows, err := q.db.Query(ctx, listActiveReminderRulesByTenant, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReminderRule{}
	for rows.Next() {
		var i ReminderRule
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.TenantID,
			&i.RuleType,
			&i.TriggerDate,
			&i.NotifyDaysBefore,
			&i.Source,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminderRulesByTenant = `-- name: ListReminderRulesByTenant :many
SELECT id, document_id, tenant_id, rule_type, trigger_date, notify_days_before, source, active, created_at
FROM reminder_rules
WHERE tenant_id = $1
ORDER BY trigger_date ASC, created_at DESC
`

type ListReminderRulesByTenantParams struct {
	TenantID string `json:"tenant_id"`
}

func (q *Queries) ListReminderRulesByTenant(ctx context.Context, arg ListReminderRulesByTenantParams) ([]ReminderRule, error) {
	rows, err := q.db.Query(ctx, listReminderRulesByTenant, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReminderRule{}
	for rows.Next() {
		var i ReminderRule
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.TenantID,
			&i.RuleType,
			&i.TriggerDate,
			&i.NotifyDaysBefore,
			&i.Source,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingReminderRules = `-- name: ListUpcomingReminderRules :many
SELECT id, document_id, tenant_id, rule_type, trigger_date, notify_days_before, source, active, created_at
FROM reminder_rules
WHERE tenant_id = $1
  AND active = true
  AND trigger_date <= CURRENT_DATE + ($2::integer)
ORDER BY trigger_date ASC
`

type ListUpcomingReminderRulesParams struct {
	TenantID   string `json:"tenant_id"`
	WithinDays int32  `json:"within_days"`
}

func (q *Queries) ListUpcomingReminderRules(ctx context.Context, arg ListUpcomingReminderRulesParams) ([]ReminderRule, error) {
	rows, err := q.db.Query(ctx, listUpcomingReminderRules, arg.TenantID, arg.WithinDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReminderRule{}
	for rows.Next() {
		var i ReminderRule
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.TenantID,
			&i.RuleType,
			&i.TriggerDate,
			&i.NotifyDaysBefore,
			&i.Source,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReminderEvent = `-- name: UpdateReminderEvent :exec
UPDATE reminder_events
SET sent_at = $1, status = $2, error_message = $3
WHERE id = $4
`

type UpdateReminderEventParams struct {
	SentAt       pgtype.Timestamptz  `json:"sent_at"`
	Status       ReminderEventStatus `json:"status"`
	ErrorMessage *string             `json:"error_message"`
	ID           string              `json:"id"`
}

func (q *Queries) UpdateReminderEvent(ctx context.Context, arg UpdateReminderEventParams) error {
	_, err := q.db.Exec(ctx, updateReminderEvent,
		arg.SentAt,
		arg.Status,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const updateReminderRule = `-- name: UpdateReminderRule :exec
UPDATE reminder_rules
SET rule_type = $1, trigger_date = $2, notify_days_before = $3, active = $4
WHERE id = $5 AND tenant_id = $6
`

type UpdateReminderRuleParams struct {
	RuleType         string      `json:"rule_type"`
	TriggerDate      pgtype.Date `json:"trigger_date"`
	NotifyDaysBefore []int32     `json:"notify_days_before"`
	Active           bool        `json:"active"`
	ID               string      `json:"id"`
	TenantID         string      `json:"tenant_id"`
}

func (q *Queries) UpdateReminderRule(ctx context.Context, arg UpdateReminderRuleParams) error {
	_, err := q.db.Exec(ctx, updateReminderRule,
		arg.RuleType,
		arg.TriggerDate,
		arg.NotifyDaysBefore,
		arg.Active,
		arg.ID,
		arg.TenantID,
	)
	return err
}
