// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchDocumentChunks = `-- name: SearchDocumentChunks :many
WITH RECURSIVE folder_ancestors AS (
  SELECT f.id AS origin_folder_id, f.id AS ancestor_id, f.parent_id, f.is_restricted, ARRAY[f.id] AS path
  FROM folders f WHERE f.org_id = $2
  UNION ALL
  SELECT fa.origin_folder_id, pf.id, pf.parent_id, pf.is_restricted, fa.path || pf.id
  FROM folders pf JOIN folder_ancestors fa ON pf.id = fa.parent_id
  WHERE NOT pf.id = ANY(fa.path) AND array_length(fa.path, 1) < 100
),
filtered_chunks AS (
  SELECT
    c.document_id,
    d.title,
    d.doc_type,
    c.id AS chunk_id,
    c.chunk_text,
    COALESCE(p.page_number, 0)::integer AS page_number,
    COALESCE(d.language, '') AS language,
    FALSE AS is_translation,
    c.embedding <=> $3::text::vector AS distance,
    GREATEST(0.0, 1 - (c.embedding <=> $3::text::vector)) AS raw_semantic_score,
    POSITION(LOWER($4) IN LOWER(c.chunk_text)) > 0 AS chunk_contains_query,
    POSITION(LOWER($4) IN LOWER(d.title)) > 0 AS title_contains_query
  FROM extracted_text_chunks c
  JOIN documents d ON c.document_id = d.id
  LEFT JOIN document_pages p ON c.page_id = p.id
  WHERE c.embedding IS NOT NULL
    AND d.tenant_id = $5
    AND d.org_id = $2
    AND ($6::text IS NULL OR d.doc_type::text = $6::text)
    AND ($7::text IS NULL OR d.language = $7::text)
    AND ($8::text IS NULL OR d.status::text = $8::text)
    AND ($9::uuid IS NULL OR d.folder_id = $9::uuid)
    AND ($10::uuid IS NULL OR c.document_id = $10::uuid)
    AND ($11::timestamptz IS NULL OR d.created_at >= $11::timestamptz)
    AND ($12::timestamptz IS NULL OR d.created_at <= $12::timestamptz)
    AND (
      cardinality($13::text[]) = 0
      OR NOT EXISTS (
        SELECT 1
        FROM unnest($13::text[]) AS required_tag(name)
        WHERE NOT EXISTS (
          SELECT 1
          FROM document_tags dt
          JOIN tags t ON t.id = dt.tag_id
          WHERE dt.document_id = d.id
            AND t.tenant_id = d.tenant_id
            AND t.name = required_tag.name
        )
      )
    )
    AND (
      $14::boolean
      OR d.owner_id = $15::uuid
      OR (NOT d.is_restricted AND NOT EXISTS (
           SELECT 1 FROM folder_ancestors fa WHERE fa.origin_folder_id=d.folder_id AND fa.is_restricted))
      OR EXISTS (SELECT 1 FROM acl_grants g
           WHERE g.resource_type='document' AND g.resource_id=d.id AND g.permission='read'
             AND ((g.principal_type='user' AND g.principal_id=$15::uuid)
               OR (g.principal_type='group' AND g.principal_id = ANY($16::uuid[]))))
      OR EXISTS (SELECT 1 FROM folder_ancestors fa
           JOIN acl_grants g ON g.resource_type='folder' AND g.resource_id=fa.ancestor_id AND g.permission='read'
           WHERE fa.origin_folder_id=d.folder_id
             AND ((g.principal_type='user' AND g.principal_id=$15::uuid)
               OR (g.principal_type='group' AND g.principal_id = ANY($16::uuid[])))))
),
scored_chunks AS (
  SELECT
    document_id,
    title,
    doc_type,
    chunk_id,
    chunk_text,
    page_number,
    language,
    is_translation,
    distance,
    GREATEST(
      LEAST(1.0, GREATEST(0.0, (raw_semantic_score - 0.4) / 0.6)),
      CASE
        WHEN LOWER(BTRIM(title)) = LOWER(BTRIM($4)) THEN 1.0
        WHEN LOWER(BTRIM(chunk_text)) = LOWER(BTRIM($4)) THEN 0.99
        WHEN chunk_contains_query THEN 0.97
        WHEN title_contains_query THEN 0.95
        ELSE 0.0
      END
    )::double precision AS score
  FROM filtered_chunks
),
vector_matches AS (
  SELECT document_id, title, doc_type, chunk_id, chunk_text, page_number, language, is_translation, distance, score
  FROM scored_chunks
  ORDER BY distance ASC
  LIMIT $1
),
lexical_matches AS (
  SELECT document_id, title, doc_type, chunk_id, chunk_text, page_number, language, is_translation, distance, score
  FROM scored_chunks
  WHERE score >= 0.95
  ORDER BY score DESC, distance ASC
  LIMIT $1
),
candidate_matches AS (
  SELECT document_id, title, doc_type, chunk_id, chunk_text, page_number, language, is_translation, distance, score FROM vector_matches
  UNION ALL
  SELECT document_id, title, doc_type, chunk_id, chunk_text, page_number, language, is_translation, distance, score FROM lexical_matches
),
deduped_matches AS (
  SELECT DISTINCT ON (chunk_id)
    document_id,
    title,
    doc_type,
    chunk_id,
    chunk_text,
    page_number,
    language,
    is_translation,
    score,
    distance
  FROM candidate_matches
  ORDER BY chunk_id, score DESC, distance ASC
)
SELECT
  document_id,
  title,
  doc_type,
  chunk_id,
  chunk_text,
  page_number,
  language,
  is_translation,
  score
FROM deduped_matches
ORDER BY score DESC
LIMIT $1
`

type SearchDocumentChunksParams struct {
	LimitCount  int32              `json:"limit_count"`
	OrgID       string             `json:"org_id"`
	QueryVector string             `json:"query_vector"`
	QueryText   string             `json:"query_text"`
	TenantID    string             `json:"tenant_id"`
	DocType     *string            `json:"doc_type"`
	Language    *string            `json:"language"`
	Status      *string            `json:"status"`
	FolderID    *string            `json:"folder_id"`
	DocumentID  *string            `json:"document_id"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	EndDate     pgtype.Timestamptz `json:"end_date"`
	Tags        []string           `json:"tags"`
	IsAdmin     bool               `json:"is_admin"`
	UserID      string             `json:"user_id"`
	GroupIds    []string           `json:"group_ids"`
}

type SearchDocumentChunksRow struct {
	DocumentID    string       `json:"document_id"`
	Title         string       `json:"title"`
	DocType       DocumentType `json:"doc_type"`
	ChunkID       string       `json:"chunk_id"`
	ChunkText     string       `json:"chunk_text"`
	PageNumber    int32        `json:"page_number"`
	Language      string       `json:"language"`
	IsTranslation bool         `json:"is_translation"`
	Score         float64      `json:"score"`
}

func (q *Queries) SearchDocumentChunks(ctx context.Context, arg SearchDocumentChunksParams) ([]SearchDocumentChunksRow, error) {
	rows, err := q.db.Query(ctx, searchDocumentChunks,
		arg.LimitCount,
		arg.OrgID,
		arg.QueryVector,
		arg.QueryText,
		arg.TenantID,
		arg.DocType,
		arg.Language,
		arg.Status,
		arg.FolderID,
		arg.DocumentID,
		arg.StartDate,
		arg.EndDate,
		arg.Tags,
		arg.IsAdmin,
		arg.UserID,
		arg.GroupIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentChunksRow{}
	for rows.Next() {
		var i SearchDocumentChunksRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.Title,
			&i.DocType,
			&i.ChunkID,
			&i.ChunkText,
			&i.PageNumber,
			&i.Language,
			&i.IsTranslation,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
