// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
)

const addTagToDocument = `-- name: AddTagToDocument :exec
INSERT INTO document_tags (document_id, tag_id, created_at)
VALUES ($1, $2, NOW())
ON CONFLICT DO NOTHING
`

type AddTagToDocumentParams struct {
	DocumentID string `json:"document_id"`
	TagID      string `json:"tag_id"`
}

func (q *Queries) AddTagToDocument(ctx context.Context, arg AddTagToDocumentParams) error {
	_, err := q.db.Exec(ctx, addTagToDocument, arg.DocumentID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :exec
INSERT INTO tags (id, tenant_id, name, created_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (tenant_id, name) DO NOTHING
`

type CreateTagParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) error {
	_, err := q.db.Exec(ctx, createTag, arg.ID, arg.TenantID, arg.Name)
	return err
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags
WHERE id = $1 AND tenant_id = $2
`

type DeleteTagParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocumentTags = `-- name: GetDocumentTags :many
SELECT t.id, t.tenant_id, t.name, t.created_at
FROM tags t
JOIN document_tags dt ON t.id = dt.tag_id
WHERE dt.document_id = $1 AND t.tenant_id = $2
ORDER BY t.name ASC
`

type GetDocumentTagsParams struct {
	DocumentID string `json:"document_id"`
	TenantID   string `json:"tenant_id"`
}

func (q *Queries) GetDocumentTags(ctx context.Context, arg GetDocumentTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getDocumentTags, arg.DocumentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, tenant_id, name, created_at
FROM tags
WHERE id = $1 AND tenant_id = $2
`

type GetTagByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetTagByID(ctx context.Context, arg GetTagByIDParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, arg.ID, arg.TenantID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, tenant_id, name, created_at
FROM tags
WHERE tenant_id = $1 AND name = $2
`

type GetTagByNameParams struct {
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, arg.TenantID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, tenant_id, name, created_at
FROM tags
WHERE tenant_id = $1
ORDER BY name ASC
LIMIT $2
`

type ListTagsParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromDocument = `-- name: RemoveTagFromDocument :exec
DELETE FROM document_tags
WHERE document_id = $1 AND tag_id = $2
`

type RemoveTagFromDocumentParams struct {
	DocumentID string `json:"document_id"`
	TagID      string `json:"tag_id"`
}

func (q *Queries) RemoveTagFromDocument(ctx context.Context, arg RemoveTagFromDocumentParams) error {
	_, err := q.db.Exec(ctx, removeTagFromDocument, arg.DocumentID, arg.TagID)
	return err
}

const searchTags = `-- name: SearchTags :many
SELECT id, tenant_id, name, created_at
FROM tags
WHERE tenant_id = $1 AND name ILIKE $2
ORDER BY name ASC
LIMIT $3
`

type SearchTagsParams struct {
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, searchTags, arg.TenantID, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
