// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, tenant_id, email, password_hash, display_name, locale, email_verified, failed_login_attempts, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	Email               string             `json:"email"`
	PasswordHash        *string            `json:"password_hash"`
	DisplayName         string             `json:"display_name"`
	Locale              string             `json:"locale"`
	EmailVerified       bool               `json:"email_verified"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Locale,
		arg.EmailVerified,
		arg.FailedLoginAttempts,
		arg.CreatedAt,
	)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, tenant_id, email, COALESCE(password_hash, '') AS password_hash, display_name, locale, email_verified,
       failed_login_attempts, locked_until, last_login_at, created_at
FROM users
WHERE email = $1
`

type FindUserByEmailParams struct {
	Email string `json:"email"`
}

type FindUserByEmailRow struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	DisplayName         string             `json:"display_name"`
	Locale              string             `json:"locale"`
	EmailVerified       bool               `json:"email_verified"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         *time.Time         `json:"locked_until"`
	LastLoginAt         *time.Time         `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, arg FindUserByEmailParams) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, arg.Email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.EmailVerified,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, tenant_id, email, COALESCE(password_hash, '') AS password_hash, display_name, locale, email_verified,
       last_login_at, created_at
FROM users
WHERE id = $1
`

type FindUserByIDParams struct {
	ID string `json:"id"`
}

type FindUserByIDRow struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	DisplayName   string             `json:"display_name"`
	Locale        string             `json:"locale"`
	EmailVerified bool               `json:"email_verified"`
	LastLoginAt   *time.Time         `json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindUserByID(ctx context.Context, arg FindUserByIDParams) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, arg.ID)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const isEmailTakenByOther = `-- name: IsEmailTakenByOther :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1 AND id <> $2)
`

type IsEmailTakenByOtherParams struct {
	Email string `json:"email"`
	ID    string `json:"id"`
}

func (q *Queries) IsEmailTakenByOther(ctx context.Context, arg IsEmailTakenByOtherParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailTakenByOther, arg.Email, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSuccessfulLoginMetadata = `-- name: UpdateSuccessfulLoginMetadata :exec
UPDATE users
SET failed_login_attempts = 0, locked_until = NULL, last_login_at = $1
WHERE id = $2
`

type UpdateSuccessfulLoginMetadataParams struct {
	LastLoginAt *time.Time `json:"last_login_at"`
	ID          string     `json:"id"`
}

func (q *Queries) UpdateSuccessfulLoginMetadata(ctx context.Context, arg UpdateSuccessfulLoginMetadataParams) error {
	_, err := q.db.Exec(ctx, updateSuccessfulLoginMetadata, arg.LastLoginAt, arg.ID)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
SET email = $1, email_verified = FALSE
WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string `json:"email"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}

const updateUserFailedLogin = `-- name: UpdateUserFailedLogin :exec
UPDATE users
SET failed_login_attempts = $1, locked_until = $2
WHERE id = $3
`

type UpdateUserFailedLoginParams struct {
	FailedLoginAttempts int32      `json:"failed_login_attempts"`
	LockedUntil         *time.Time `json:"locked_until"`
	ID                  string     `json:"id"`
}

func (q *Queries) UpdateUserFailedLogin(ctx context.Context, arg UpdateUserFailedLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserFailedLogin, arg.FailedLoginAttempts, arg.LockedUntil, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, failed_login_attempts = 0, locked_until = NULL
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash *string `json:"password_hash"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET display_name = $1, locale = $2
WHERE id = $3
`

type UpdateUserProfileParams struct {
	DisplayName string `json:"display_name"`
	Locale      string `json:"locale"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.DisplayName, arg.Locale, arg.ID)
	return err
}
